name: 'Upload Videos'
description: 'Upload videos to S3 and show logs on failure'
inputs:
  region:
    description: 'AWS region'
    required: true
    default: 'eu-west-1'
  bucket:
    description: 'S3 bucket name'
    required: true
    default: 'readonlyrest-data'
runs:
  using: 'composite'
  steps:
    - name: Upload videos to S3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set region ${{ inputs.region }}
        aws s3 cp results/videos/ s3://${{ inputs.bucket }}/e2e-tests/build_${{ github.run_id }}/${{ matrix.env }}/${{ matrix.version }}/ --recursive