apiVersion: v1
kind: Service
metadata:
  name: apm-np
  namespace: default
spec:
  selector:
    apm.k8s.elastic.co/name: apm-server-quickstart
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  type: NodePort