apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: quickstart
  namespace: default
spec:
  version: ${ES_VERSION}
  count: 1
  config:
    apm-server:
      rum:
        enabled: true
      kibana:
        enabled: false
    output:
      elasticsearch:
        hosts: [ "https://quickstart-es-http.default.svc:9200" ]
        username: "apm"
        password: "test"
        ssl:
          enabled: true
    logging:
      level: "debug"
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart