apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 3000
      targetPort: 30014
  type: NodePort