apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: node-apm-app:latest  # Use the image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: apm-cert-volume
              mountPath: /example-app/certs
              readOnly: true
      volumes:
        - name: apm-cert-volume
          secret:
            secretName: apm-server-quickstart-apm-kibana-ca
