apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: ${KBN_VERSION}
  image: beshultd/kibana-readonlyrest:${KBN_VERSION}-ror-latest
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    # csp needs to be disabled to let cypress e2e tests works
    csp.strict: false
    csp.warnLegacyBrowsers: false
    # KBN ROR settings
    readonlyrest_kbn:
      cookiePass: '12312313123213123213123adadasdasdasd'
      logLevel: trace
      store_sessions_in_index: true
    ${ELATICSEARCH_USER}    
    ${ELATICSEARCH_PASSWORD}
              
  podTemplate:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: kibana
          env:
            - name: ROR_ACTIVATION_KEY
              value: "${ROR_ACTIVATION_KEY}"
            - name: I_UNDERSTAND_AND_ACCEPT_KBN_PATCHING
              value: "yes"
