apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart-node-apm-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-apm-app
  template:
    metadata:
      labels:
        app: node-apm-app
    spec:
      containers:
        - name: node-apm-app
          image: node-apm-app:latest  # Use the image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: apm-cert-volume
              mountPath: /example-app/certs
              readOnly: true
          env:
            - name: APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: quickstart-apm-token
                  key: secret-token
      volumes:
        - name: apm-cert-volume
          secret:
            secretName: quickstart-apm-kibana-ca
