apiVersion: v1
kind: Service
metadata:
  name: node-apm-app-np
spec:
  selector:
    app: node-apm-app
  ports:
    - name: http
      port: 3000
      nodePort: 30014
      targetPort: 3000
  type: NodePort