name: End-to-end test workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  e2e-tests-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        ./run.sh
      env:
        ROR_ACTIVATION_KEY: $(ROR_KBN_LICENSE)
    - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
      displayName: 'S3 Upload Videos & logs'
      inputs:
        awsCredentials: 'S3 creds'
        regionName: 'eu-west-1'
        bucketName: 'readonlyrest-data'
        sourceFolder: 'results/videos'
        globExpressions: |
          *.mp4
          *.log
        targetFolder: 'e2e-tests/build_$(Build.BuildID)/8x'
      continueOnError: true
      condition: failed()