name: End-to-end test workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  e2e-tests-8x-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        ./docker-based-ror-dev-env/runE2ETests8xInDocker.sh
      env:
        ROR_ACTIVATION_KEY: ${{ secrets.ROR_KBN_LICENSE }}
    - name: S3 Upload Videos & logs
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp results/videos/* 's3://readonlyrest-data/e2e-tests/build_${{ github.run_id }}/8x' --recursive
  e2e-tests-7x-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        ./docker-based-ror-dev-env/runE2ETests7xInDocker.sh
      env:
        ROR_ACTIVATION_KEY: ${{ secrets.ROR_KBN_LICENSE }}
    - name: S3 Upload Videos & logs
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp results/videos/* 's3://readonlyrest-data/e2e-tests/build_${{ github.run_id }}/7x' --recursive
